/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdatvedelmiTajekoztatoRouteImport } from './routes/adatvedelmi-tajekoztato'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdotanacsadasRouteImport } from './routes/adotanacsadas'
import { Route as AszfRouteImport } from './routes/aszf'
import { Route as CegauditRouteImport } from './routes/cegaudit'
import { Route as CookieTajekoztatoRouteImport } from './routes/cookie-tajekoztato'
import { Route as DigitalisIdomegtakaritasiAuditRouteImport } from './routes/digitalis-idomegtakaritasi-audit'
import { Route as ElallasASzerzodestolRouteImport } from './routes/elallas-a-szerzodestol'
import { Route as EnRouteImport } from './routes/en'
import { Route as EvRouteImport } from './routes/ev'
import { Route as EvKonyvelesRouteImport } from './routes/ev-konyveles'
import { Route as FintechEsBiRouteImport } from './routes/fintech-es-bi'
import { Route as FizetesEsTeljesitesRouteImport } from './routes/fizetes-es-teljesites'
import { Route as FogyasztovedelemRouteImport } from './routes/fogyasztovedelem'
import { Route as HirlevelMegerositesRouteImport } from './routes/hirlevel-megerosites'
import { Route as ImpresszumRouteImport } from './routes/impresszum'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as KontrollingRouteImport } from './routes/kontrolling'
import { Route as KonyvelesRouteImport } from './routes/konyveles'
import { Route as KonyveloirodaAuditRouteImport } from './routes/konyveloiroda-audit'
import { Route as KonyvvizsgalatRouteImport } from './routes/konyvvizsgalat'
import { Route as KonzultacioRouteImport } from './routes/konzultacio'
import { Route as LeiratkozasRouteImport } from './routes/leiratkozas'
import { Route as LetoltesHibaRouteImport } from './routes/letoltes-hiba'
import { Route as MegrendelesRouteImport } from './routes/megrendeles'
import { Route as OktatasRouteImport } from './routes/oktatas'
import { Route as RolamRouteImport } from './routes/rolam'
import { Route as SeRouteImport } from './routes/se'
import { Route as SeBookkeepingRouteImport } from './routes/se-bookkeeping'
import { Route as SzolgaltatasaimRouteImport } from './routes/szolgaltatasaim'
import { Route as TermekeimRouteImport } from './routes/termekeim'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBillingoEllenorzesRouteImport } from './routes/admin.billingo-ellenorzes'
import { Route as AdminFelhasznalokRouteImport } from './routes/admin.felhasznalok'
import { Route as AdminFizetesTesztRouteImport } from './routes/admin.fizetes-teszt'
import { Route as AdminFrissVerzioRouteImport } from './routes/admin.friss-verzio'
import { Route as AdminHirlevelRouteImport } from './routes/admin.hirlevel'
import { Route as AdminJelszoRouteImport } from './routes/admin.jelszo'
import { Route as AdminKatalogusEllenorzesRouteImport } from './routes/admin.katalogus-ellenorzes'
import { Route as AdminKuponokRouteImport } from './routes/admin.kuponok'
import { Route as AdminNavEllenorzesRouteImport } from './routes/admin.nav-ellenorzes'
import { Route as AdminRendelesiAuditRouteImport } from './routes/admin.rendelesi-audit'
import { Route as AdminStatisztikaRouteImport } from './routes/admin.statisztika'
import { Route as AdminSzamlazasRouteImport } from './routes/admin.szamlazas'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as EnAccountingFirmAuditRouteImport } from './routes/en.accounting-firm-audit'
import { Route as EnBookkeepingRouteImport } from './routes/en.bookkeeping'
import { Route as EnCompanyAuditRouteImport } from './routes/en.company-audit'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnControllingRouteImport } from './routes/en.controlling'
import { Route as EnDigitalTimeSavingAuditRouteImport } from './routes/en.digital-time-saving-audit'
import { Route as EnFintechAndBiRouteImport } from './routes/en.fintech-and-bi'
import { Route as EnServicesRouteImport } from './routes/en.services'
import { Route as EnSoleTraderBookkeepingRouteImport } from './routes/en.sole-trader-bookkeeping'
import { Route as EnStatutoryAuditRouteImport } from './routes/en.statutory-audit'
import { Route as EnTaxAdvisoryRouteImport } from './routes/en.tax-advisory'
import { Route as EnTrainingRouteImport } from './routes/en.training'
import { Route as KalkulatorokIndexRouteImport } from './routes/kalkulatorok.index'
import { Route as KalkulatorokAtalanyadoRouteImport } from './routes/kalkulatorok.atalanyado'
import { Route as KalkulatorokBertesztRouteImport } from './routes/kalkulatorok.berteszt'
import { Route as KalkulatorokInvoiceDatesRouteImport } from './routes/kalkulatorok.invoice-dates'
import { Route as KalkulatorokJovedelemadoRouteImport } from './routes/kalkulatorok.jovedelemado'
import { Route as KalkulatorokSzamlaDatumokRouteImport } from './routes/kalkulatorok.szamla-datumok'
import { Route as MegrendelesKoszonjukRouteImport } from './routes/megrendeles_.koszonjuk'
import { Route as TermekSlugRouteImport } from './routes/termek.$slug'
import { Route as TermekA60OsszesitoNyilatkozatXmlRouteImport } from './routes/termek.a60-osszesito-nyilatkozat-xml'
import { Route as TermekAdofolyoszamlaEgyeztetoRouteImport } from './routes/termek.adofolyoszamla-egyezteto'
import { Route as TermekAfaEv65XmlGeneraloRouteImport } from './routes/termek.afa-ev65-xml-generalo'
import { Route as TermekAuditxmlEllenorzoJavitoRouteImport } from './routes/termek.auditxml-ellenorzo-javito'
import { Route as TermekBerszamfejtoRouteImport } from './routes/termek.berszamfejto'
import { Route as TermekBeszamoloRouteImport } from './routes/termek.beszamolo'
import { Route as TermekCegkivonatExcelKonverterRouteImport } from './routes/termek.cegkivonat-excel-konverter'
import { Route as TermekDevizabankRouteImport } from './routes/termek.devizabank'
import { Route as TermekHaviRiportRouteImport } from './routes/termek.havi-riport'
import { Route as TermekHaviRiportEnRouteImport } from './routes/termek.havi-riport-en'
import { Route as TermekIfrsKonszolidaloRouteImport } from './routes/termek.ifrs-konszolidalo'
import { Route as TermekIngatlanalapMnbJelentesElokeszitoRouteImport } from './routes/termek.ingatlanalap-mnb-jelentes-elokeszito'
import { Route as TermekKamatlekerdezoPotlekszamitoRouteImport } from './routes/termek.kamatlekerdezo-potlekszamito'
import { Route as TermekKulcsNyitoVegyesKonyveloRouteImport } from './routes/termek.kulcs-nyito-vegyes-konyvelo'
import { Route as TermekKulcsSoftKulfoldiSzamlaImportRouteImport } from './routes/termek.kulcs-soft-kulfoldi-szamla-import'
import { Route as TermekMnbEraJelentesgeneratorRouteImport } from './routes/termek.mnb-era-jelentesgenerator'
import { Route as TermekNavOnlineSzamlaLetoltoRouteImport } from './routes/termek.nav-online-szamla-letolto'
import { Route as TermekNavPenztargepLetoltoRouteImport } from './routes/termek.nav-penztargep-letolto'
import { Route as TermekNavTorzsszamPartnerellenorzoRouteImport } from './routes/termek.nav-torzsszam-partnerellenorzo'
import { Route as TermekPdfExcelKonverterRouteImport } from './routes/termek.pdf-excel-konverter'
import { Route as TermekPenzszamKulfoldiSzamlaImportRouteImport } from './routes/termek.penzszam-kulfoldi-szamla-import'
import { Route as TermekRlbBankKonverterRouteImport } from './routes/termek.rlb-bank-konverter'
import { Route as TermekRlbBankKonverterProRouteImport } from './routes/termek.rlb-bank-konverter-pro'
import { Route as TermekRlbKulfoldiSzamlaImportRouteImport } from './routes/termek.rlb-kulfoldi-szamla-import'
import { Route as TermekRlbNyitoVegyesKonyveloRouteImport } from './routes/termek.rlb-nyito-vegyes-konyvelo'
import { Route as TermekSupNyitoVegyesKonyveloRouteImport } from './routes/termek.sup-nyito-vegyes-konyvelo'
import { Route as TermekSzamviteliKonszolidaloRouteImport } from './routes/termek.szamviteli-konszolidalo'
import { Route as TermekTelefonszamlaKonyveloRouteImport } from './routes/termek.telefonszamla-konyvelo'
import { Route as TermekUgyfelkapuTotpManagerRouteImport } from './routes/termek.ugyfelkapu-totp-manager'
import { Route as TermekUniverzalisBankKonverterRouteImport } from './routes/termek.univerzalis-bank-konverter'
import { Route as TermekUtalasiCsomagKeszitoRouteImport } from './routes/termek.utalasi-csomag-keszito'
import { Route as TermekUtnyilvantartasKikuldetesiRendelvenyRouteImport } from './routes/termek.utnyilvantartas-kikuldetesi-rendelveny'
import { Route as TermekWifiJelszoNezoRouteImport } from './routes/termek.wifi-jelszo-nezo'
import { Route as ApiPublicBillingoWebhookRouteImport } from './routes/api/public/billingo/webhook'
import { Route as ApiPublicKatalogusAuditCronRouteImport } from './routes/api/public/katalogus-audit/cron'
import { Route as ApiPublicLetoltesTokenRouteImport } from './routes/api/public/letoltes/$token'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdatvedelmiTajekoztatoRoute = AdatvedelmiTajekoztatoRouteImport.update({
  id: '/adatvedelmi-tajekoztato',
  path: '/adatvedelmi-tajekoztato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdotanacsadasRoute = AdotanacsadasRouteImport.update({
  id: '/adotanacsadas',
  path: '/adotanacsadas',
  getParentRoute: () => rootRouteImport,
} as any)
const AszfRoute = AszfRouteImport.update({
  id: '/aszf',
  path: '/aszf',
  getParentRoute: () => rootRouteImport,
} as any)
const CegauditRoute = CegauditRouteImport.update({
  id: '/cegaudit',
  path: '/cegaudit',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieTajekoztatoRoute = CookieTajekoztatoRouteImport.update({
  id: '/cookie-tajekoztato',
  path: '/cookie-tajekoztato',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalisIdomegtakaritasiAuditRoute =
  DigitalisIdomegtakaritasiAuditRouteImport.update({
    id: '/digitalis-idomegtakaritasi-audit',
    path: '/digitalis-idomegtakaritasi-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ElallasASzerzodestolRoute = ElallasASzerzodestolRouteImport.update({
  id: '/elallas-a-szerzodestol',
  path: '/elallas-a-szerzodestol',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const EvRoute = EvRouteImport.update({
  id: '/ev',
  path: '/ev',
  getParentRoute: () => rootRouteImport,
} as any)
const EvKonyvelesRoute = EvKonyvelesRouteImport.update({
  id: '/ev-konyveles',
  path: '/ev-konyveles',
  getParentRoute: () => rootRouteImport,
} as any)
const FintechEsBiRoute = FintechEsBiRouteImport.update({
  id: '/fintech-es-bi',
  path: '/fintech-es-bi',
  getParentRoute: () => rootRouteImport,
} as any)
const FizetesEsTeljesitesRoute = FizetesEsTeljesitesRouteImport.update({
  id: '/fizetes-es-teljesites',
  path: '/fizetes-es-teljesites',
  getParentRoute: () => rootRouteImport,
} as any)
const FogyasztovedelemRoute = FogyasztovedelemRouteImport.update({
  id: '/fogyasztovedelem',
  path: '/fogyasztovedelem',
  getParentRoute: () => rootRouteImport,
} as any)
const HirlevelMegerositesRoute = HirlevelMegerositesRouteImport.update({
  id: '/hirlevel-megerosites',
  path: '/hirlevel-megerosites',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpresszumRoute = ImpresszumRouteImport.update({
  id: '/impresszum',
  path: '/impresszum',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const KontrollingRoute = KontrollingRouteImport.update({
  id: '/kontrolling',
  path: '/kontrolling',
  getParentRoute: () => rootRouteImport,
} as any)
const KonyvelesRoute = KonyvelesRouteImport.update({
  id: '/konyveles',
  path: '/konyveles',
  getParentRoute: () => rootRouteImport,
} as any)
const KonyveloirodaAuditRoute = KonyveloirodaAuditRouteImport.update({
  id: '/konyveloiroda-audit',
  path: '/konyveloiroda-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const KonyvvizsgalatRoute = KonyvvizsgalatRouteImport.update({
  id: '/konyvvizsgalat',
  path: '/konyvvizsgalat',
  getParentRoute: () => rootRouteImport,
} as any)
const KonzultacioRoute = KonzultacioRouteImport.update({
  id: '/konzultacio',
  path: '/konzultacio',
  getParentRoute: () => rootRouteImport,
} as any)
const LeiratkozasRoute = LeiratkozasRouteImport.update({
  id: '/leiratkozas',
  path: '/leiratkozas',
  getParentRoute: () => rootRouteImport,
} as any)
const LetoltesHibaRoute = LetoltesHibaRouteImport.update({
  id: '/letoltes-hiba',
  path: '/letoltes-hiba',
  getParentRoute: () => rootRouteImport,
} as any)
const MegrendelesRoute = MegrendelesRouteImport.update({
  id: '/megrendeles',
  path: '/megrendeles',
  getParentRoute: () => rootRouteImport,
} as any)
const OktatasRoute = OktatasRouteImport.update({
  id: '/oktatas',
  path: '/oktatas',
  getParentRoute: () => rootRouteImport,
} as any)
const RolamRoute = RolamRouteImport.update({
  id: '/rolam',
  path: '/rolam',
  getParentRoute: () => rootRouteImport,
} as any)
const SeRoute = SeRouteImport.update({
  id: '/se',
  path: '/se',
  getParentRoute: () => rootRouteImport,
} as any)
const SeBookkeepingRoute = SeBookkeepingRouteImport.update({
  id: '/se-bookkeeping',
  path: '/se-bookkeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const SzolgaltatasaimRoute = SzolgaltatasaimRouteImport.update({
  id: '/szolgaltatasaim',
  path: '/szolgaltatasaim',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekeimRoute = TermekeimRouteImport.update({
  id: '/termekeim',
  path: '/termekeim',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingoEllenorzesRoute = AdminBillingoEllenorzesRouteImport.update({
  id: '/billingo-ellenorzes',
  path: '/billingo-ellenorzes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFelhasznalokRoute = AdminFelhasznalokRouteImport.update({
  id: '/felhasznalok',
  path: '/felhasznalok',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFizetesTesztRoute = AdminFizetesTesztRouteImport.update({
  id: '/fizetes-teszt',
  path: '/fizetes-teszt',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFrissVerzioRoute = AdminFrissVerzioRouteImport.update({
  id: '/friss-verzio',
  path: '/friss-verzio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHirlevelRoute = AdminHirlevelRouteImport.update({
  id: '/hirlevel',
  path: '/hirlevel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJelszoRoute = AdminJelszoRouteImport.update({
  id: '/jelszo',
  path: '/jelszo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKatalogusEllenorzesRoute =
  AdminKatalogusEllenorzesRouteImport.update({
    id: '/katalogus-ellenorzes',
    path: '/katalogus-ellenorzes',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminKuponokRoute = AdminKuponokRouteImport.update({
  id: '/kuponok',
  path: '/kuponok',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavEllenorzesRoute = AdminNavEllenorzesRouteImport.update({
  id: '/nav-ellenorzes',
  path: '/nav-ellenorzes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRendelesiAuditRoute = AdminRendelesiAuditRouteImport.update({
  id: '/rendelesi-audit',
  path: '/rendelesi-audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatisztikaRoute = AdminStatisztikaRouteImport.update({
  id: '/statisztika',
  path: '/statisztika',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSzamlazasRoute = AdminSzamlazasRouteImport.update({
  id: '/szamlazas',
  path: '/szamlazas',
  getParentRoute: () => AdminRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const EnAccountingFirmAuditRoute = EnAccountingFirmAuditRouteImport.update({
  id: '/accounting-firm-audit',
  path: '/accounting-firm-audit',
  getParentRoute: () => EnRoute,
} as any)
const EnBookkeepingRoute = EnBookkeepingRouteImport.update({
  id: '/bookkeeping',
  path: '/bookkeeping',
  getParentRoute: () => EnRoute,
} as any)
const EnCompanyAuditRoute = EnCompanyAuditRouteImport.update({
  id: '/company-audit',
  path: '/company-audit',
  getParentRoute: () => EnRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRoute,
} as any)
const EnControllingRoute = EnControllingRouteImport.update({
  id: '/controlling',
  path: '/controlling',
  getParentRoute: () => EnRoute,
} as any)
const EnDigitalTimeSavingAuditRoute =
  EnDigitalTimeSavingAuditRouteImport.update({
    id: '/digital-time-saving-audit',
    path: '/digital-time-saving-audit',
    getParentRoute: () => EnRoute,
  } as any)
const EnFintechAndBiRoute = EnFintechAndBiRouteImport.update({
  id: '/fintech-and-bi',
  path: '/fintech-and-bi',
  getParentRoute: () => EnRoute,
} as any)
const EnServicesRoute = EnServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => EnRoute,
} as any)
const EnSoleTraderBookkeepingRoute = EnSoleTraderBookkeepingRouteImport.update({
  id: '/sole-trader-bookkeeping',
  path: '/sole-trader-bookkeeping',
  getParentRoute: () => EnRoute,
} as any)
const EnStatutoryAuditRoute = EnStatutoryAuditRouteImport.update({
  id: '/statutory-audit',
  path: '/statutory-audit',
  getParentRoute: () => EnRoute,
} as any)
const EnTaxAdvisoryRoute = EnTaxAdvisoryRouteImport.update({
  id: '/tax-advisory',
  path: '/tax-advisory',
  getParentRoute: () => EnRoute,
} as any)
const EnTrainingRoute = EnTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => EnRoute,
} as any)
const KalkulatorokIndexRoute = KalkulatorokIndexRouteImport.update({
  id: '/kalkulatorok/',
  path: '/kalkulatorok/',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatorokAtalanyadoRoute = KalkulatorokAtalanyadoRouteImport.update({
  id: '/kalkulatorok/atalanyado',
  path: '/kalkulatorok/atalanyado',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatorokBertesztRoute = KalkulatorokBertesztRouteImport.update({
  id: '/kalkulatorok/berteszt',
  path: '/kalkulatorok/berteszt',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatorokInvoiceDatesRoute =
  KalkulatorokInvoiceDatesRouteImport.update({
    id: '/kalkulatorok/invoice-dates',
    path: '/kalkulatorok/invoice-dates',
    getParentRoute: () => rootRouteImport,
  } as any)
const KalkulatorokJovedelemadoRoute =
  KalkulatorokJovedelemadoRouteImport.update({
    id: '/kalkulatorok/jovedelemado',
    path: '/kalkulatorok/jovedelemado',
    getParentRoute: () => rootRouteImport,
  } as any)
const KalkulatorokSzamlaDatumokRoute =
  KalkulatorokSzamlaDatumokRouteImport.update({
    id: '/kalkulatorok/szamla-datumok',
    path: '/kalkulatorok/szamla-datumok',
    getParentRoute: () => rootRouteImport,
  } as any)
const MegrendelesKoszonjukRoute = MegrendelesKoszonjukRouteImport.update({
  id: '/megrendeles_/koszonjuk',
  path: '/megrendeles/koszonjuk',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekSlugRoute = TermekSlugRouteImport.update({
  id: '/termek/$slug',
  path: '/termek/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekA60OsszesitoNyilatkozatXmlRoute =
  TermekA60OsszesitoNyilatkozatXmlRouteImport.update({
    id: '/termek/a60-osszesito-nyilatkozat-xml',
    path: '/termek/a60-osszesito-nyilatkozat-xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekAdofolyoszamlaEgyeztetoRoute =
  TermekAdofolyoszamlaEgyeztetoRouteImport.update({
    id: '/termek/adofolyoszamla-egyezteto',
    path: '/termek/adofolyoszamla-egyezteto',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekAfaEv65XmlGeneraloRoute =
  TermekAfaEv65XmlGeneraloRouteImport.update({
    id: '/termek/afa-ev65-xml-generalo',
    path: '/termek/afa-ev65-xml-generalo',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekAuditxmlEllenorzoJavitoRoute =
  TermekAuditxmlEllenorzoJavitoRouteImport.update({
    id: '/termek/auditxml-ellenorzo-javito',
    path: '/termek/auditxml-ellenorzo-javito',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekBerszamfejtoRoute = TermekBerszamfejtoRouteImport.update({
  id: '/termek/berszamfejto',
  path: '/termek/berszamfejto',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekBeszamoloRoute = TermekBeszamoloRouteImport.update({
  id: '/termek/beszamolo',
  path: '/termek/beszamolo',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekCegkivonatExcelKonverterRoute =
  TermekCegkivonatExcelKonverterRouteImport.update({
    id: '/termek/cegkivonat-excel-konverter',
    path: '/termek/cegkivonat-excel-konverter',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekDevizabankRoute = TermekDevizabankRouteImport.update({
  id: '/termek/devizabank',
  path: '/termek/devizabank',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekHaviRiportRoute = TermekHaviRiportRouteImport.update({
  id: '/termek/havi-riport',
  path: '/termek/havi-riport',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekHaviRiportEnRoute = TermekHaviRiportEnRouteImport.update({
  id: '/termek/havi-riport-en',
  path: '/termek/havi-riport-en',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekIfrsKonszolidaloRoute = TermekIfrsKonszolidaloRouteImport.update({
  id: '/termek/ifrs-konszolidalo',
  path: '/termek/ifrs-konszolidalo',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekIngatlanalapMnbJelentesElokeszitoRoute =
  TermekIngatlanalapMnbJelentesElokeszitoRouteImport.update({
    id: '/termek/ingatlanalap-mnb-jelentes-elokeszito',
    path: '/termek/ingatlanalap-mnb-jelentes-elokeszito',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekKamatlekerdezoPotlekszamitoRoute =
  TermekKamatlekerdezoPotlekszamitoRouteImport.update({
    id: '/termek/kamatlekerdezo-potlekszamito',
    path: '/termek/kamatlekerdezo-potlekszamito',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekKulcsNyitoVegyesKonyveloRoute =
  TermekKulcsNyitoVegyesKonyveloRouteImport.update({
    id: '/termek/kulcs-nyito-vegyes-konyvelo',
    path: '/termek/kulcs-nyito-vegyes-konyvelo',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekKulcsSoftKulfoldiSzamlaImportRoute =
  TermekKulcsSoftKulfoldiSzamlaImportRouteImport.update({
    id: '/termek/kulcs-soft-kulfoldi-szamla-import',
    path: '/termek/kulcs-soft-kulfoldi-szamla-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekMnbEraJelentesgeneratorRoute =
  TermekMnbEraJelentesgeneratorRouteImport.update({
    id: '/termek/mnb-era-jelentesgenerator',
    path: '/termek/mnb-era-jelentesgenerator',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekNavOnlineSzamlaLetoltoRoute =
  TermekNavOnlineSzamlaLetoltoRouteImport.update({
    id: '/termek/nav-online-szamla-letolto',
    path: '/termek/nav-online-szamla-letolto',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekNavPenztargepLetoltoRoute =
  TermekNavPenztargepLetoltoRouteImport.update({
    id: '/termek/nav-penztargep-letolto',
    path: '/termek/nav-penztargep-letolto',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekNavTorzsszamPartnerellenorzoRoute =
  TermekNavTorzsszamPartnerellenorzoRouteImport.update({
    id: '/termek/nav-torzsszam-partnerellenorzo',
    path: '/termek/nav-torzsszam-partnerellenorzo',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekPdfExcelKonverterRoute = TermekPdfExcelKonverterRouteImport.update({
  id: '/termek/pdf-excel-konverter',
  path: '/termek/pdf-excel-konverter',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekPenzszamKulfoldiSzamlaImportRoute =
  TermekPenzszamKulfoldiSzamlaImportRouteImport.update({
    id: '/termek/penzszam-kulfoldi-szamla-import',
    path: '/termek/penzszam-kulfoldi-szamla-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekRlbBankKonverterRoute = TermekRlbBankKonverterRouteImport.update({
  id: '/termek/rlb-bank-konverter',
  path: '/termek/rlb-bank-konverter',
  getParentRoute: () => rootRouteImport,
} as any)
const TermekRlbBankKonverterProRoute =
  TermekRlbBankKonverterProRouteImport.update({
    id: '/termek/rlb-bank-konverter-pro',
    path: '/termek/rlb-bank-konverter-pro',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekRlbKulfoldiSzamlaImportRoute =
  TermekRlbKulfoldiSzamlaImportRouteImport.update({
    id: '/termek/rlb-kulfoldi-szamla-import',
    path: '/termek/rlb-kulfoldi-szamla-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekRlbNyitoVegyesKonyveloRoute =
  TermekRlbNyitoVegyesKonyveloRouteImport.update({
    id: '/termek/rlb-nyito-vegyes-konyvelo',
    path: '/termek/rlb-nyito-vegyes-konyvelo',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekSupNyitoVegyesKonyveloRoute =
  TermekSupNyitoVegyesKonyveloRouteImport.update({
    id: '/termek/sup-nyito-vegyes-konyvelo',
    path: '/termek/sup-nyito-vegyes-konyvelo',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekSzamviteliKonszolidaloRoute =
  TermekSzamviteliKonszolidaloRouteImport.update({
    id: '/termek/szamviteli-konszolidalo',
    path: '/termek/szamviteli-konszolidalo',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekTelefonszamlaKonyveloRoute =
  TermekTelefonszamlaKonyveloRouteImport.update({
    id: '/termek/telefonszamla-konyvelo',
    path: '/termek/telefonszamla-konyvelo',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekUgyfelkapuTotpManagerRoute =
  TermekUgyfelkapuTotpManagerRouteImport.update({
    id: '/termek/ugyfelkapu-totp-manager',
    path: '/termek/ugyfelkapu-totp-manager',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekUniverzalisBankKonverterRoute =
  TermekUniverzalisBankKonverterRouteImport.update({
    id: '/termek/univerzalis-bank-konverter',
    path: '/termek/univerzalis-bank-konverter',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekUtalasiCsomagKeszitoRoute =
  TermekUtalasiCsomagKeszitoRouteImport.update({
    id: '/termek/utalasi-csomag-keszito',
    path: '/termek/utalasi-csomag-keszito',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekUtnyilvantartasKikuldetesiRendelvenyRoute =
  TermekUtnyilvantartasKikuldetesiRendelvenyRouteImport.update({
    id: '/termek/utnyilvantartas-kikuldetesi-rendelveny',
    path: '/termek/utnyilvantartas-kikuldetesi-rendelveny',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermekWifiJelszoNezoRoute = TermekWifiJelszoNezoRouteImport.update({
  id: '/termek/wifi-jelszo-nezo',
  path: '/termek/wifi-jelszo-nezo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingoWebhookRoute =
  ApiPublicBillingoWebhookRouteImport.update({
    id: '/api/public/billingo/webhook',
    path: '/api/public/billingo/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKatalogusAuditCronRoute =
  ApiPublicKatalogusAuditCronRouteImport.update({
    id: '/api/public/katalogus-audit/cron',
    path: '/api/public/katalogus-audit/cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLetoltesTokenRoute = ApiPublicLetoltesTokenRouteImport.update({
  id: '/api/public/letoltes/$token',
  path: '/api/public/letoltes/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adatvedelmi-tajekoztato': typeof AdatvedelmiTajekoztatoRoute
  '/admin': typeof AdminRouteWithChildren
  '/adotanacsadas': typeof AdotanacsadasRoute
  '/aszf': typeof AszfRoute
  '/cegaudit': typeof CegauditRoute
  '/cookie-tajekoztato': typeof CookieTajekoztatoRoute
  '/digitalis-idomegtakaritasi-audit': typeof DigitalisIdomegtakaritasiAuditRoute
  '/elallas-a-szerzodestol': typeof ElallasASzerzodestolRoute
  '/en': typeof EnRouteWithChildren
  '/ev': typeof EvRoute
  '/ev-konyveles': typeof EvKonyvelesRoute
  '/fintech-es-bi': typeof FintechEsBiRoute
  '/fizetes-es-teljesites': typeof FizetesEsTeljesitesRoute
  '/fogyasztovedelem': typeof FogyasztovedelemRoute
  '/hirlevel-megerosites': typeof HirlevelMegerositesRoute
  '/impresszum': typeof ImpresszumRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/kontrolling': typeof KontrollingRoute
  '/konyveles': typeof KonyvelesRoute
  '/konyveloiroda-audit': typeof KonyveloirodaAuditRoute
  '/konyvvizsgalat': typeof KonyvvizsgalatRoute
  '/konzultacio': typeof KonzultacioRoute
  '/leiratkozas': typeof LeiratkozasRoute
  '/letoltes-hiba': typeof LetoltesHibaRoute
  '/megrendeles': typeof MegrendelesRoute
  '/oktatas': typeof OktatasRoute
  '/rolam': typeof RolamRoute
  '/se': typeof SeRoute
  '/se-bookkeeping': typeof SeBookkeepingRoute
  '/szolgaltatasaim': typeof SzolgaltatasaimRoute
  '/termekeim': typeof TermekeimRoute
  '/admin/billingo-ellenorzes': typeof AdminBillingoEllenorzesRoute
  '/admin/felhasznalok': typeof AdminFelhasznalokRoute
  '/admin/fizetes-teszt': typeof AdminFizetesTesztRoute
  '/admin/friss-verzio': typeof AdminFrissVerzioRoute
  '/admin/hirlevel': typeof AdminHirlevelRoute
  '/admin/jelszo': typeof AdminJelszoRoute
  '/admin/katalogus-ellenorzes': typeof AdminKatalogusEllenorzesRoute
  '/admin/kuponok': typeof AdminKuponokRoute
  '/admin/nav-ellenorzes': typeof AdminNavEllenorzesRoute
  '/admin/rendelesi-audit': typeof AdminRendelesiAuditRoute
  '/admin/statisztika': typeof AdminStatisztikaRoute
  '/admin/szamlazas': typeof AdminSzamlazasRoute
  '/en/about': typeof EnAboutRoute
  '/en/accounting-firm-audit': typeof EnAccountingFirmAuditRoute
  '/en/bookkeeping': typeof EnBookkeepingRoute
  '/en/company-audit': typeof EnCompanyAuditRoute
  '/en/contact': typeof EnContactRoute
  '/en/controlling': typeof EnControllingRoute
  '/en/digital-time-saving-audit': typeof EnDigitalTimeSavingAuditRoute
  '/en/fintech-and-bi': typeof EnFintechAndBiRoute
  '/en/services': typeof EnServicesRoute
  '/en/sole-trader-bookkeeping': typeof EnSoleTraderBookkeepingRoute
  '/en/statutory-audit': typeof EnStatutoryAuditRoute
  '/en/tax-advisory': typeof EnTaxAdvisoryRoute
  '/en/training': typeof EnTrainingRoute
  '/kalkulatorok/atalanyado': typeof KalkulatorokAtalanyadoRoute
  '/kalkulatorok/berteszt': typeof KalkulatorokBertesztRoute
  '/kalkulatorok/invoice-dates': typeof KalkulatorokInvoiceDatesRoute
  '/kalkulatorok/jovedelemado': typeof KalkulatorokJovedelemadoRoute
  '/kalkulatorok/szamla-datumok': typeof KalkulatorokSzamlaDatumokRoute
  '/megrendeles/koszonjuk': typeof MegrendelesKoszonjukRoute
  '/termek/$slug': typeof TermekSlugRoute
  '/termek/a60-osszesito-nyilatkozat-xml': typeof TermekA60OsszesitoNyilatkozatXmlRoute
  '/termek/adofolyoszamla-egyezteto': typeof TermekAdofolyoszamlaEgyeztetoRoute
  '/termek/afa-ev65-xml-generalo': typeof TermekAfaEv65XmlGeneraloRoute
  '/termek/auditxml-ellenorzo-javito': typeof TermekAuditxmlEllenorzoJavitoRoute
  '/termek/berszamfejto': typeof TermekBerszamfejtoRoute
  '/termek/beszamolo': typeof TermekBeszamoloRoute
  '/termek/cegkivonat-excel-konverter': typeof TermekCegkivonatExcelKonverterRoute
  '/termek/devizabank': typeof TermekDevizabankRoute
  '/termek/havi-riport': typeof TermekHaviRiportRoute
  '/termek/havi-riport-en': typeof TermekHaviRiportEnRoute
  '/termek/ifrs-konszolidalo': typeof TermekIfrsKonszolidaloRoute
  '/termek/ingatlanalap-mnb-jelentes-elokeszito': typeof TermekIngatlanalapMnbJelentesElokeszitoRoute
  '/termek/kamatlekerdezo-potlekszamito': typeof TermekKamatlekerdezoPotlekszamitoRoute
  '/termek/kulcs-nyito-vegyes-konyvelo': typeof TermekKulcsNyitoVegyesKonyveloRoute
  '/termek/kulcs-soft-kulfoldi-szamla-import': typeof TermekKulcsSoftKulfoldiSzamlaImportRoute
  '/termek/mnb-era-jelentesgenerator': typeof TermekMnbEraJelentesgeneratorRoute
  '/termek/nav-online-szamla-letolto': typeof TermekNavOnlineSzamlaLetoltoRoute
  '/termek/nav-penztargep-letolto': typeof TermekNavPenztargepLetoltoRoute
  '/termek/nav-torzsszam-partnerellenorzo': typeof TermekNavTorzsszamPartnerellenorzoRoute
  '/termek/pdf-excel-konverter': typeof TermekPdfExcelKonverterRoute
  '/termek/penzszam-kulfoldi-szamla-import': typeof TermekPenzszamKulfoldiSzamlaImportRoute
  '/termek/rlb-bank-konverter': typeof TermekRlbBankKonverterRoute
  '/termek/rlb-bank-konverter-pro': typeof TermekRlbBankKonverterProRoute
  '/termek/rlb-kulfoldi-szamla-import': typeof TermekRlbKulfoldiSzamlaImportRoute
  '/termek/rlb-nyito-vegyes-konyvelo': typeof TermekRlbNyitoVegyesKonyveloRoute
  '/termek/sup-nyito-vegyes-konyvelo': typeof TermekSupNyitoVegyesKonyveloRoute
  '/termek/szamviteli-konszolidalo': typeof TermekSzamviteliKonszolidaloRoute
  '/termek/telefonszamla-konyvelo': typeof TermekTelefonszamlaKonyveloRoute
  '/termek/ugyfelkapu-totp-manager': typeof TermekUgyfelkapuTotpManagerRoute
  '/termek/univerzalis-bank-konverter': typeof TermekUniverzalisBankKonverterRoute
  '/termek/utalasi-csomag-keszito': typeof TermekUtalasiCsomagKeszitoRoute
  '/termek/utnyilvantartas-kikuldetesi-rendelveny': typeof TermekUtnyilvantartasKikuldetesiRendelvenyRoute
  '/termek/wifi-jelszo-nezo': typeof TermekWifiJelszoNezoRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/kalkulatorok/': typeof KalkulatorokIndexRoute
  '/api/public/billingo/webhook': typeof ApiPublicBillingoWebhookRoute
  '/api/public/katalogus-audit/cron': typeof ApiPublicKatalogusAuditCronRoute
  '/api/public/letoltes/$token': typeof ApiPublicLetoltesTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adatvedelmi-tajekoztato': typeof AdatvedelmiTajekoztatoRoute
  '/adotanacsadas': typeof AdotanacsadasRoute
  '/aszf': typeof AszfRoute
  '/cegaudit': typeof CegauditRoute
  '/cookie-tajekoztato': typeof CookieTajekoztatoRoute
  '/digitalis-idomegtakaritasi-audit': typeof DigitalisIdomegtakaritasiAuditRoute
  '/elallas-a-szerzodestol': typeof ElallasASzerzodestolRoute
  '/ev': typeof EvRoute
  '/ev-konyveles': typeof EvKonyvelesRoute
  '/fintech-es-bi': typeof FintechEsBiRoute
  '/fizetes-es-teljesites': typeof FizetesEsTeljesitesRoute
  '/fogyasztovedelem': typeof FogyasztovedelemRoute
  '/hirlevel-megerosites': typeof HirlevelMegerositesRoute
  '/impresszum': typeof ImpresszumRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/kontrolling': typeof KontrollingRoute
  '/konyveles': typeof KonyvelesRoute
  '/konyveloiroda-audit': typeof KonyveloirodaAuditRoute
  '/konyvvizsgalat': typeof KonyvvizsgalatRoute
  '/konzultacio': typeof KonzultacioRoute
  '/leiratkozas': typeof LeiratkozasRoute
  '/letoltes-hiba': typeof LetoltesHibaRoute
  '/megrendeles': typeof MegrendelesRoute
  '/oktatas': typeof OktatasRoute
  '/rolam': typeof RolamRoute
  '/se': typeof SeRoute
  '/se-bookkeeping': typeof SeBookkeepingRoute
  '/szolgaltatasaim': typeof SzolgaltatasaimRoute
  '/termekeim': typeof TermekeimRoute
  '/admin/billingo-ellenorzes': typeof AdminBillingoEllenorzesRoute
  '/admin/felhasznalok': typeof AdminFelhasznalokRoute
  '/admin/fizetes-teszt': typeof AdminFizetesTesztRoute
  '/admin/friss-verzio': typeof AdminFrissVerzioRoute
  '/admin/hirlevel': typeof AdminHirlevelRoute
  '/admin/jelszo': typeof AdminJelszoRoute
  '/admin/katalogus-ellenorzes': typeof AdminKatalogusEllenorzesRoute
  '/admin/kuponok': typeof AdminKuponokRoute
  '/admin/nav-ellenorzes': typeof AdminNavEllenorzesRoute
  '/admin/rendelesi-audit': typeof AdminRendelesiAuditRoute
  '/admin/statisztika': typeof AdminStatisztikaRoute
  '/admin/szamlazas': typeof AdminSzamlazasRoute
  '/en/about': typeof EnAboutRoute
  '/en/accounting-firm-audit': typeof EnAccountingFirmAuditRoute
  '/en/bookkeeping': typeof EnBookkeepingRoute
  '/en/company-audit': typeof EnCompanyAuditRoute
  '/en/contact': typeof EnContactRoute
  '/en/controlling': typeof EnControllingRoute
  '/en/digital-time-saving-audit': typeof EnDigitalTimeSavingAuditRoute
  '/en/fintech-and-bi': typeof EnFintechAndBiRoute
  '/en/services': typeof EnServicesRoute
  '/en/sole-trader-bookkeeping': typeof EnSoleTraderBookkeepingRoute
  '/en/statutory-audit': typeof EnStatutoryAuditRoute
  '/en/tax-advisory': typeof EnTaxAdvisoryRoute
  '/en/training': typeof EnTrainingRoute
  '/kalkulatorok/atalanyado': typeof KalkulatorokAtalanyadoRoute
  '/kalkulatorok/berteszt': typeof KalkulatorokBertesztRoute
  '/kalkulatorok/invoice-dates': typeof KalkulatorokInvoiceDatesRoute
  '/kalkulatorok/jovedelemado': typeof KalkulatorokJovedelemadoRoute
  '/kalkulatorok/szamla-datumok': typeof KalkulatorokSzamlaDatumokRoute
  '/megrendeles/koszonjuk': typeof MegrendelesKoszonjukRoute
  '/termek/$slug': typeof TermekSlugRoute
  '/termek/a60-osszesito-nyilatkozat-xml': typeof TermekA60OsszesitoNyilatkozatXmlRoute
  '/termek/adofolyoszamla-egyezteto': typeof TermekAdofolyoszamlaEgyeztetoRoute
  '/termek/afa-ev65-xml-generalo': typeof TermekAfaEv65XmlGeneraloRoute
  '/termek/auditxml-ellenorzo-javito': typeof TermekAuditxmlEllenorzoJavitoRoute
  '/termek/berszamfejto': typeof TermekBerszamfejtoRoute
  '/termek/beszamolo': typeof TermekBeszamoloRoute
  '/termek/cegkivonat-excel-konverter': typeof TermekCegkivonatExcelKonverterRoute
  '/termek/devizabank': typeof TermekDevizabankRoute
  '/termek/havi-riport': typeof TermekHaviRiportRoute
  '/termek/havi-riport-en': typeof TermekHaviRiportEnRoute
  '/termek/ifrs-konszolidalo': typeof TermekIfrsKonszolidaloRoute
  '/termek/ingatlanalap-mnb-jelentes-elokeszito': typeof TermekIngatlanalapMnbJelentesElokeszitoRoute
  '/termek/kamatlekerdezo-potlekszamito': typeof TermekKamatlekerdezoPotlekszamitoRoute
  '/termek/kulcs-nyito-vegyes-konyvelo': typeof TermekKulcsNyitoVegyesKonyveloRoute
  '/termek/kulcs-soft-kulfoldi-szamla-import': typeof TermekKulcsSoftKulfoldiSzamlaImportRoute
  '/termek/mnb-era-jelentesgenerator': typeof TermekMnbEraJelentesgeneratorRoute
  '/termek/nav-online-szamla-letolto': typeof TermekNavOnlineSzamlaLetoltoRoute
  '/termek/nav-penztargep-letolto': typeof TermekNavPenztargepLetoltoRoute
  '/termek/nav-torzsszam-partnerellenorzo': typeof TermekNavTorzsszamPartnerellenorzoRoute
  '/termek/pdf-excel-konverter': typeof TermekPdfExcelKonverterRoute
  '/termek/penzszam-kulfoldi-szamla-import': typeof TermekPenzszamKulfoldiSzamlaImportRoute
  '/termek/rlb-bank-konverter': typeof TermekRlbBankKonverterRoute
  '/termek/rlb-bank-konverter-pro': typeof TermekRlbBankKonverterProRoute
  '/termek/rlb-kulfoldi-szamla-import': typeof TermekRlbKulfoldiSzamlaImportRoute
  '/termek/rlb-nyito-vegyes-konyvelo': typeof TermekRlbNyitoVegyesKonyveloRoute
  '/termek/sup-nyito-vegyes-konyvelo': typeof TermekSupNyitoVegyesKonyveloRoute
  '/termek/szamviteli-konszolidalo': typeof TermekSzamviteliKonszolidaloRoute
  '/termek/telefonszamla-konyvelo': typeof TermekTelefonszamlaKonyveloRoute
  '/termek/ugyfelkapu-totp-manager': typeof TermekUgyfelkapuTotpManagerRoute
  '/termek/univerzalis-bank-konverter': typeof TermekUniverzalisBankKonverterRoute
  '/termek/utalasi-csomag-keszito': typeof TermekUtalasiCsomagKeszitoRoute
  '/termek/utnyilvantartas-kikuldetesi-rendelveny': typeof TermekUtnyilvantartasKikuldetesiRendelvenyRoute
  '/termek/wifi-jelszo-nezo': typeof TermekWifiJelszoNezoRoute
  '/admin': typeof AdminIndexRoute
  '/en': typeof EnIndexRoute
  '/kalkulatorok': typeof KalkulatorokIndexRoute
  '/api/public/billingo/webhook': typeof ApiPublicBillingoWebhookRoute
  '/api/public/katalogus-audit/cron': typeof ApiPublicKatalogusAuditCronRoute
  '/api/public/letoltes/$token': typeof ApiPublicLetoltesTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adatvedelmi-tajekoztato': typeof AdatvedelmiTajekoztatoRoute
  '/admin': typeof AdminRouteWithChildren
  '/adotanacsadas': typeof AdotanacsadasRoute
  '/aszf': typeof AszfRoute
  '/cegaudit': typeof CegauditRoute
  '/cookie-tajekoztato': typeof CookieTajekoztatoRoute
  '/digitalis-idomegtakaritasi-audit': typeof DigitalisIdomegtakaritasiAuditRoute
  '/elallas-a-szerzodestol': typeof ElallasASzerzodestolRoute
  '/en': typeof EnRouteWithChildren
  '/ev': typeof EvRoute
  '/ev-konyveles': typeof EvKonyvelesRoute
  '/fintech-es-bi': typeof FintechEsBiRoute
  '/fizetes-es-teljesites': typeof FizetesEsTeljesitesRoute
  '/fogyasztovedelem': typeof FogyasztovedelemRoute
  '/hirlevel-megerosites': typeof HirlevelMegerositesRoute
  '/impresszum': typeof ImpresszumRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/kontrolling': typeof KontrollingRoute
  '/konyveles': typeof KonyvelesRoute
  '/konyveloiroda-audit': typeof KonyveloirodaAuditRoute
  '/konyvvizsgalat': typeof KonyvvizsgalatRoute
  '/konzultacio': typeof KonzultacioRoute
  '/leiratkozas': typeof LeiratkozasRoute
  '/letoltes-hiba': typeof LetoltesHibaRoute
  '/megrendeles': typeof MegrendelesRoute
  '/oktatas': typeof OktatasRoute
  '/rolam': typeof RolamRoute
  '/se': typeof SeRoute
  '/se-bookkeeping': typeof SeBookkeepingRoute
  '/szolgaltatasaim': typeof SzolgaltatasaimRoute
  '/termekeim': typeof TermekeimRoute
  '/admin/billingo-ellenorzes': typeof AdminBillingoEllenorzesRoute
  '/admin/felhasznalok': typeof AdminFelhasznalokRoute
  '/admin/fizetes-teszt': typeof AdminFizetesTesztRoute
  '/admin/friss-verzio': typeof AdminFrissVerzioRoute
  '/admin/hirlevel': typeof AdminHirlevelRoute
  '/admin/jelszo': typeof AdminJelszoRoute
  '/admin/katalogus-ellenorzes': typeof AdminKatalogusEllenorzesRoute
  '/admin/kuponok': typeof AdminKuponokRoute
  '/admin/nav-ellenorzes': typeof AdminNavEllenorzesRoute
  '/admin/rendelesi-audit': typeof AdminRendelesiAuditRoute
  '/admin/statisztika': typeof AdminStatisztikaRoute
  '/admin/szamlazas': typeof AdminSzamlazasRoute
  '/en/about': typeof EnAboutRoute
  '/en/accounting-firm-audit': typeof EnAccountingFirmAuditRoute
  '/en/bookkeeping': typeof EnBookkeepingRoute
  '/en/company-audit': typeof EnCompanyAuditRoute
  '/en/contact': typeof EnContactRoute
  '/en/controlling': typeof EnControllingRoute
  '/en/digital-time-saving-audit': typeof EnDigitalTimeSavingAuditRoute
  '/en/fintech-and-bi': typeof EnFintechAndBiRoute
  '/en/services': typeof EnServicesRoute
  '/en/sole-trader-bookkeeping': typeof EnSoleTraderBookkeepingRoute
  '/en/statutory-audit': typeof EnStatutoryAuditRoute
  '/en/tax-advisory': typeof EnTaxAdvisoryRoute
  '/en/training': typeof EnTrainingRoute
  '/kalkulatorok/atalanyado': typeof KalkulatorokAtalanyadoRoute
  '/kalkulatorok/berteszt': typeof KalkulatorokBertesztRoute
  '/kalkulatorok/invoice-dates': typeof KalkulatorokInvoiceDatesRoute
  '/kalkulatorok/jovedelemado': typeof KalkulatorokJovedelemadoRoute
  '/kalkulatorok/szamla-datumok': typeof KalkulatorokSzamlaDatumokRoute
  '/megrendeles_/koszonjuk': typeof MegrendelesKoszonjukRoute
  '/termek/$slug': typeof TermekSlugRoute
  '/termek/a60-osszesito-nyilatkozat-xml': typeof TermekA60OsszesitoNyilatkozatXmlRoute
  '/termek/adofolyoszamla-egyezteto': typeof TermekAdofolyoszamlaEgyeztetoRoute
  '/termek/afa-ev65-xml-generalo': typeof TermekAfaEv65XmlGeneraloRoute
  '/termek/auditxml-ellenorzo-javito': typeof TermekAuditxmlEllenorzoJavitoRoute
  '/termek/berszamfejto': typeof TermekBerszamfejtoRoute
  '/termek/beszamolo': typeof TermekBeszamoloRoute
  '/termek/cegkivonat-excel-konverter': typeof TermekCegkivonatExcelKonverterRoute
  '/termek/devizabank': typeof TermekDevizabankRoute
  '/termek/havi-riport': typeof TermekHaviRiportRoute
  '/termek/havi-riport-en': typeof TermekHaviRiportEnRoute
  '/termek/ifrs-konszolidalo': typeof TermekIfrsKonszolidaloRoute
  '/termek/ingatlanalap-mnb-jelentes-elokeszito': typeof TermekIngatlanalapMnbJelentesElokeszitoRoute
  '/termek/kamatlekerdezo-potlekszamito': typeof TermekKamatlekerdezoPotlekszamitoRoute
  '/termek/kulcs-nyito-vegyes-konyvelo': typeof TermekKulcsNyitoVegyesKonyveloRoute
  '/termek/kulcs-soft-kulfoldi-szamla-import': typeof TermekKulcsSoftKulfoldiSzamlaImportRoute
  '/termek/mnb-era-jelentesgenerator': typeof TermekMnbEraJelentesgeneratorRoute
  '/termek/nav-online-szamla-letolto': typeof TermekNavOnlineSzamlaLetoltoRoute
  '/termek/nav-penztargep-letolto': typeof TermekNavPenztargepLetoltoRoute
  '/termek/nav-torzsszam-partnerellenorzo': typeof TermekNavTorzsszamPartnerellenorzoRoute
  '/termek/pdf-excel-konverter': typeof TermekPdfExcelKonverterRoute
  '/termek/penzszam-kulfoldi-szamla-import': typeof TermekPenzszamKulfoldiSzamlaImportRoute
  '/termek/rlb-bank-konverter': typeof TermekRlbBankKonverterRoute
  '/termek/rlb-bank-konverter-pro': typeof TermekRlbBankKonverterProRoute
  '/termek/rlb-kulfoldi-szamla-import': typeof TermekRlbKulfoldiSzamlaImportRoute
  '/termek/rlb-nyito-vegyes-konyvelo': typeof TermekRlbNyitoVegyesKonyveloRoute
  '/termek/sup-nyito-vegyes-konyvelo': typeof TermekSupNyitoVegyesKonyveloRoute
  '/termek/szamviteli-konszolidalo': typeof TermekSzamviteliKonszolidaloRoute
  '/termek/telefonszamla-konyvelo': typeof TermekTelefonszamlaKonyveloRoute
  '/termek/ugyfelkapu-totp-manager': typeof TermekUgyfelkapuTotpManagerRoute
  '/termek/univerzalis-bank-konverter': typeof TermekUniverzalisBankKonverterRoute
  '/termek/utalasi-csomag-keszito': typeof TermekUtalasiCsomagKeszitoRoute
  '/termek/utnyilvantartas-kikuldetesi-rendelveny': typeof TermekUtnyilvantartasKikuldetesiRendelvenyRoute
  '/termek/wifi-jelszo-nezo': typeof TermekWifiJelszoNezoRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/kalkulatorok/': typeof KalkulatorokIndexRoute
  '/api/public/billingo/webhook': typeof ApiPublicBillingoWebhookRoute
  '/api/public/katalogus-audit/cron': typeof ApiPublicKatalogusAuditCronRoute
  '/api/public/letoltes/$token': typeof ApiPublicLetoltesTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adatvedelmi-tajekoztato'
    | '/admin'
    | '/adotanacsadas'
    | '/aszf'
    | '/cegaudit'
    | '/cookie-tajekoztato'
    | '/digitalis-idomegtakaritasi-audit'
    | '/elallas-a-szerzodestol'
    | '/en'
    | '/ev'
    | '/ev-konyveles'
    | '/fintech-es-bi'
    | '/fizetes-es-teljesites'
    | '/fogyasztovedelem'
    | '/hirlevel-megerosites'
    | '/impresszum'
    | '/kapcsolat'
    | '/kontrolling'
    | '/konyveles'
    | '/konyveloiroda-audit'
    | '/konyvvizsgalat'
    | '/konzultacio'
    | '/leiratkozas'
    | '/letoltes-hiba'
    | '/megrendeles'
    | '/oktatas'
    | '/rolam'
    | '/se'
    | '/se-bookkeeping'
    | '/szolgaltatasaim'
    | '/termekeim'
    | '/admin/billingo-ellenorzes'
    | '/admin/felhasznalok'
    | '/admin/fizetes-teszt'
    | '/admin/friss-verzio'
    | '/admin/hirlevel'
    | '/admin/jelszo'
    | '/admin/katalogus-ellenorzes'
    | '/admin/kuponok'
    | '/admin/nav-ellenorzes'
    | '/admin/rendelesi-audit'
    | '/admin/statisztika'
    | '/admin/szamlazas'
    | '/en/about'
    | '/en/accounting-firm-audit'
    | '/en/bookkeeping'
    | '/en/company-audit'
    | '/en/contact'
    | '/en/controlling'
    | '/en/digital-time-saving-audit'
    | '/en/fintech-and-bi'
    | '/en/services'
    | '/en/sole-trader-bookkeeping'
    | '/en/statutory-audit'
    | '/en/tax-advisory'
    | '/en/training'
    | '/kalkulatorok/atalanyado'
    | '/kalkulatorok/berteszt'
    | '/kalkulatorok/invoice-dates'
    | '/kalkulatorok/jovedelemado'
    | '/kalkulatorok/szamla-datumok'
    | '/megrendeles/koszonjuk'
    | '/termek/$slug'
    | '/termek/a60-osszesito-nyilatkozat-xml'
    | '/termek/adofolyoszamla-egyezteto'
    | '/termek/afa-ev65-xml-generalo'
    | '/termek/auditxml-ellenorzo-javito'
    | '/termek/berszamfejto'
    | '/termek/beszamolo'
    | '/termek/cegkivonat-excel-konverter'
    | '/termek/devizabank'
    | '/termek/havi-riport'
    | '/termek/havi-riport-en'
    | '/termek/ifrs-konszolidalo'
    | '/termek/ingatlanalap-mnb-jelentes-elokeszito'
    | '/termek/kamatlekerdezo-potlekszamito'
    | '/termek/kulcs-nyito-vegyes-konyvelo'
    | '/termek/kulcs-soft-kulfoldi-szamla-import'
    | '/termek/mnb-era-jelentesgenerator'
    | '/termek/nav-online-szamla-letolto'
    | '/termek/nav-penztargep-letolto'
    | '/termek/nav-torzsszam-partnerellenorzo'
    | '/termek/pdf-excel-konverter'
    | '/termek/penzszam-kulfoldi-szamla-import'
    | '/termek/rlb-bank-konverter'
    | '/termek/rlb-bank-konverter-pro'
    | '/termek/rlb-kulfoldi-szamla-import'
    | '/termek/rlb-nyito-vegyes-konyvelo'
    | '/termek/sup-nyito-vegyes-konyvelo'
    | '/termek/szamviteli-konszolidalo'
    | '/termek/telefonszamla-konyvelo'
    | '/termek/ugyfelkapu-totp-manager'
    | '/termek/univerzalis-bank-konverter'
    | '/termek/utalasi-csomag-keszito'
    | '/termek/utnyilvantartas-kikuldetesi-rendelveny'
    | '/termek/wifi-jelszo-nezo'
    | '/admin/'
    | '/en/'
    | '/kalkulatorok/'
    | '/api/public/billingo/webhook'
    | '/api/public/katalogus-audit/cron'
    | '/api/public/letoltes/$token'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adatvedelmi-tajekoztato'
    | '/adotanacsadas'
    | '/aszf'
    | '/cegaudit'
    | '/cookie-tajekoztato'
    | '/digitalis-idomegtakaritasi-audit'
    | '/elallas-a-szerzodestol'
    | '/ev'
    | '/ev-konyveles'
    | '/fintech-es-bi'
    | '/fizetes-es-teljesites'
    | '/fogyasztovedelem'
    | '/hirlevel-megerosites'
    | '/impresszum'
    | '/kapcsolat'
    | '/kontrolling'
    | '/konyveles'
    | '/konyveloiroda-audit'
    | '/konyvvizsgalat'
    | '/konzultacio'
    | '/leiratkozas'
    | '/letoltes-hiba'
    | '/megrendeles'
    | '/oktatas'
    | '/rolam'
    | '/se'
    | '/se-bookkeeping'
    | '/szolgaltatasaim'
    | '/termekeim'
    | '/admin/billingo-ellenorzes'
    | '/admin/felhasznalok'
    | '/admin/fizetes-teszt'
    | '/admin/friss-verzio'
    | '/admin/hirlevel'
    | '/admin/jelszo'
    | '/admin/katalogus-ellenorzes'
    | '/admin/kuponok'
    | '/admin/nav-ellenorzes'
    | '/admin/rendelesi-audit'
    | '/admin/statisztika'
    | '/admin/szamlazas'
    | '/en/about'
    | '/en/accounting-firm-audit'
    | '/en/bookkeeping'
    | '/en/company-audit'
    | '/en/contact'
    | '/en/controlling'
    | '/en/digital-time-saving-audit'
    | '/en/fintech-and-bi'
    | '/en/services'
    | '/en/sole-trader-bookkeeping'
    | '/en/statutory-audit'
    | '/en/tax-advisory'
    | '/en/training'
    | '/kalkulatorok/atalanyado'
    | '/kalkulatorok/berteszt'
    | '/kalkulatorok/invoice-dates'
    | '/kalkulatorok/jovedelemado'
    | '/kalkulatorok/szamla-datumok'
    | '/megrendeles/koszonjuk'
    | '/termek/$slug'
    | '/termek/a60-osszesito-nyilatkozat-xml'
    | '/termek/adofolyoszamla-egyezteto'
    | '/termek/afa-ev65-xml-generalo'
    | '/termek/auditxml-ellenorzo-javito'
    | '/termek/berszamfejto'
    | '/termek/beszamolo'
    | '/termek/cegkivonat-excel-konverter'
    | '/termek/devizabank'
    | '/termek/havi-riport'
    | '/termek/havi-riport-en'
    | '/termek/ifrs-konszolidalo'
    | '/termek/ingatlanalap-mnb-jelentes-elokeszito'
    | '/termek/kamatlekerdezo-potlekszamito'
    | '/termek/kulcs-nyito-vegyes-konyvelo'
    | '/termek/kulcs-soft-kulfoldi-szamla-import'
    | '/termek/mnb-era-jelentesgenerator'
    | '/termek/nav-online-szamla-letolto'
    | '/termek/nav-penztargep-letolto'
    | '/termek/nav-torzsszam-partnerellenorzo'
    | '/termek/pdf-excel-konverter'
    | '/termek/penzszam-kulfoldi-szamla-import'
    | '/termek/rlb-bank-konverter'
    | '/termek/rlb-bank-konverter-pro'
    | '/termek/rlb-kulfoldi-szamla-import'
    | '/termek/rlb-nyito-vegyes-konyvelo'
    | '/termek/sup-nyito-vegyes-konyvelo'
    | '/termek/szamviteli-konszolidalo'
    | '/termek/telefonszamla-konyvelo'
    | '/termek/ugyfelkapu-totp-manager'
    | '/termek/univerzalis-bank-konverter'
    | '/termek/utalasi-csomag-keszito'
    | '/termek/utnyilvantartas-kikuldetesi-rendelveny'
    | '/termek/wifi-jelszo-nezo'
    | '/admin'
    | '/en'
    | '/kalkulatorok'
    | '/api/public/billingo/webhook'
    | '/api/public/katalogus-audit/cron'
    | '/api/public/letoltes/$token'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/adatvedelmi-tajekoztato'
    | '/admin'
    | '/adotanacsadas'
    | '/aszf'
    | '/cegaudit'
    | '/cookie-tajekoztato'
    | '/digitalis-idomegtakaritasi-audit'
    | '/elallas-a-szerzodestol'
    | '/en'
    | '/ev'
    | '/ev-konyveles'
    | '/fintech-es-bi'
    | '/fizetes-es-teljesites'
    | '/fogyasztovedelem'
    | '/hirlevel-megerosites'
    | '/impresszum'
    | '/kapcsolat'
    | '/kontrolling'
    | '/konyveles'
    | '/konyveloiroda-audit'
    | '/konyvvizsgalat'
    | '/konzultacio'
    | '/leiratkozas'
    | '/letoltes-hiba'
    | '/megrendeles'
    | '/oktatas'
    | '/rolam'
    | '/se'
    | '/se-bookkeeping'
    | '/szolgaltatasaim'
    | '/termekeim'
    | '/admin/billingo-ellenorzes'
    | '/admin/felhasznalok'
    | '/admin/fizetes-teszt'
    | '/admin/friss-verzio'
    | '/admin/hirlevel'
    | '/admin/jelszo'
    | '/admin/katalogus-ellenorzes'
    | '/admin/kuponok'
    | '/admin/nav-ellenorzes'
    | '/admin/rendelesi-audit'
    | '/admin/statisztika'
    | '/admin/szamlazas'
    | '/en/about'
    | '/en/accounting-firm-audit'
    | '/en/bookkeeping'
    | '/en/company-audit'
    | '/en/contact'
    | '/en/controlling'
    | '/en/digital-time-saving-audit'
    | '/en/fintech-and-bi'
    | '/en/services'
    | '/en/sole-trader-bookkeeping'
    | '/en/statutory-audit'
    | '/en/tax-advisory'
    | '/en/training'
    | '/kalkulatorok/atalanyado'
    | '/kalkulatorok/berteszt'
    | '/kalkulatorok/invoice-dates'
    | '/kalkulatorok/jovedelemado'
    | '/kalkulatorok/szamla-datumok'
    | '/megrendeles_/koszonjuk'
    | '/termek/$slug'
    | '/termek/a60-osszesito-nyilatkozat-xml'
    | '/termek/adofolyoszamla-egyezteto'
    | '/termek/afa-ev65-xml-generalo'
    | '/termek/auditxml-ellenorzo-javito'
    | '/termek/berszamfejto'
    | '/termek/beszamolo'
    | '/termek/cegkivonat-excel-konverter'
    | '/termek/devizabank'
    | '/termek/havi-riport'
    | '/termek/havi-riport-en'
    | '/termek/ifrs-konszolidalo'
    | '/termek/ingatlanalap-mnb-jelentes-elokeszito'
    | '/termek/kamatlekerdezo-potlekszamito'
    | '/termek/kulcs-nyito-vegyes-konyvelo'
    | '/termek/kulcs-soft-kulfoldi-szamla-import'
    | '/termek/mnb-era-jelentesgenerator'
    | '/termek/nav-online-szamla-letolto'
    | '/termek/nav-penztargep-letolto'
    | '/termek/nav-torzsszam-partnerellenorzo'
    | '/termek/pdf-excel-konverter'
    | '/termek/penzszam-kulfoldi-szamla-import'
    | '/termek/rlb-bank-konverter'
    | '/termek/rlb-bank-konverter-pro'
    | '/termek/rlb-kulfoldi-szamla-import'
    | '/termek/rlb-nyito-vegyes-konyvelo'
    | '/termek/sup-nyito-vegyes-konyvelo'
    | '/termek/szamviteli-konszolidalo'
    | '/termek/telefonszamla-konyvelo'
    | '/termek/ugyfelkapu-totp-manager'
    | '/termek/univerzalis-bank-konverter'
    | '/termek/utalasi-csomag-keszito'
    | '/termek/utnyilvantartas-kikuldetesi-rendelveny'
    | '/termek/wifi-jelszo-nezo'
    | '/admin/'
    | '/en/'
    | '/kalkulatorok/'
    | '/api/public/billingo/webhook'
    | '/api/public/katalogus-audit/cron'
    | '/api/public/letoltes/$token'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdatvedelmiTajekoztatoRoute: typeof AdatvedelmiTajekoztatoRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdotanacsadasRoute: typeof AdotanacsadasRoute
  AszfRoute: typeof AszfRoute
  CegauditRoute: typeof CegauditRoute
  CookieTajekoztatoRoute: typeof CookieTajekoztatoRoute
  DigitalisIdomegtakaritasiAuditRoute: typeof DigitalisIdomegtakaritasiAuditRoute
  ElallasASzerzodestolRoute: typeof ElallasASzerzodestolRoute
  EnRoute: typeof EnRouteWithChildren
  EvRoute: typeof EvRoute
  EvKonyvelesRoute: typeof EvKonyvelesRoute
  FintechEsBiRoute: typeof FintechEsBiRoute
  FizetesEsTeljesitesRoute: typeof FizetesEsTeljesitesRoute
  FogyasztovedelemRoute: typeof FogyasztovedelemRoute
  HirlevelMegerositesRoute: typeof HirlevelMegerositesRoute
  ImpresszumRoute: typeof ImpresszumRoute
  KapcsolatRoute: typeof KapcsolatRoute
  KontrollingRoute: typeof KontrollingRoute
  KonyvelesRoute: typeof KonyvelesRoute
  KonyveloirodaAuditRoute: typeof KonyveloirodaAuditRoute
  KonyvvizsgalatRoute: typeof KonyvvizsgalatRoute
  KonzultacioRoute: typeof KonzultacioRoute
  LeiratkozasRoute: typeof LeiratkozasRoute
  LetoltesHibaRoute: typeof LetoltesHibaRoute
  MegrendelesRoute: typeof MegrendelesRoute
  OktatasRoute: typeof OktatasRoute
  RolamRoute: typeof RolamRoute
  SeRoute: typeof SeRoute
  SeBookkeepingRoute: typeof SeBookkeepingRoute
  SzolgaltatasaimRoute: typeof SzolgaltatasaimRoute
  TermekeimRoute: typeof TermekeimRoute
  KalkulatorokAtalanyadoRoute: typeof KalkulatorokAtalanyadoRoute
  KalkulatorokBertesztRoute: typeof KalkulatorokBertesztRoute
  KalkulatorokInvoiceDatesRoute: typeof KalkulatorokInvoiceDatesRoute
  KalkulatorokJovedelemadoRoute: typeof KalkulatorokJovedelemadoRoute
  KalkulatorokSzamlaDatumokRoute: typeof KalkulatorokSzamlaDatumokRoute
  MegrendelesKoszonjukRoute: typeof MegrendelesKoszonjukRoute
  TermekSlugRoute: typeof TermekSlugRoute
  TermekA60OsszesitoNyilatkozatXmlRoute: typeof TermekA60OsszesitoNyilatkozatXmlRoute
  TermekAdofolyoszamlaEgyeztetoRoute: typeof TermekAdofolyoszamlaEgyeztetoRoute
  TermekAfaEv65XmlGeneraloRoute: typeof TermekAfaEv65XmlGeneraloRoute
  TermekAuditxmlEllenorzoJavitoRoute: typeof TermekAuditxmlEllenorzoJavitoRoute
  TermekBerszamfejtoRoute: typeof TermekBerszamfejtoRoute
  TermekBeszamoloRoute: typeof TermekBeszamoloRoute
  TermekCegkivonatExcelKonverterRoute: typeof TermekCegkivonatExcelKonverterRoute
  TermekDevizabankRoute: typeof TermekDevizabankRoute
  TermekHaviRiportRoute: typeof TermekHaviRiportRoute
  TermekHaviRiportEnRoute: typeof TermekHaviRiportEnRoute
  TermekIfrsKonszolidaloRoute: typeof TermekIfrsKonszolidaloRoute
  TermekIngatlanalapMnbJelentesElokeszitoRoute: typeof TermekIngatlanalapMnbJelentesElokeszitoRoute
  TermekKamatlekerdezoPotlekszamitoRoute: typeof TermekKamatlekerdezoPotlekszamitoRoute
  TermekKulcsNyitoVegyesKonyveloRoute: typeof TermekKulcsNyitoVegyesKonyveloRoute
  TermekKulcsSoftKulfoldiSzamlaImportRoute: typeof TermekKulcsSoftKulfoldiSzamlaImportRoute
  TermekMnbEraJelentesgeneratorRoute: typeof TermekMnbEraJelentesgeneratorRoute
  TermekNavOnlineSzamlaLetoltoRoute: typeof TermekNavOnlineSzamlaLetoltoRoute
  TermekNavPenztargepLetoltoRoute: typeof TermekNavPenztargepLetoltoRoute
  TermekNavTorzsszamPartnerellenorzoRoute: typeof TermekNavTorzsszamPartnerellenorzoRoute
  TermekPdfExcelKonverterRoute: typeof TermekPdfExcelKonverterRoute
  TermekPenzszamKulfoldiSzamlaImportRoute: typeof TermekPenzszamKulfoldiSzamlaImportRoute
  TermekRlbBankKonverterRoute: typeof TermekRlbBankKonverterRoute
  TermekRlbBankKonverterProRoute: typeof TermekRlbBankKonverterProRoute
  TermekRlbKulfoldiSzamlaImportRoute: typeof TermekRlbKulfoldiSzamlaImportRoute
  TermekRlbNyitoVegyesKonyveloRoute: typeof TermekRlbNyitoVegyesKonyveloRoute
  TermekSupNyitoVegyesKonyveloRoute: typeof TermekSupNyitoVegyesKonyveloRoute
  TermekSzamviteliKonszolidaloRoute: typeof TermekSzamviteliKonszolidaloRoute
  TermekTelefonszamlaKonyveloRoute: typeof TermekTelefonszamlaKonyveloRoute
  TermekUgyfelkapuTotpManagerRoute: typeof TermekUgyfelkapuTotpManagerRoute
  TermekUniverzalisBankKonverterRoute: typeof TermekUniverzalisBankKonverterRoute
  TermekUtalasiCsomagKeszitoRoute: typeof TermekUtalasiCsomagKeszitoRoute
  TermekUtnyilvantartasKikuldetesiRendelvenyRoute: typeof TermekUtnyilvantartasKikuldetesiRendelvenyRoute
  TermekWifiJelszoNezoRoute: typeof TermekWifiJelszoNezoRoute
  KalkulatorokIndexRoute: typeof KalkulatorokIndexRoute
  ApiPublicBillingoWebhookRoute: typeof ApiPublicBillingoWebhookRoute
  ApiPublicKatalogusAuditCronRoute: typeof ApiPublicKatalogusAuditCronRoute
  ApiPublicLetoltesTokenRoute: typeof ApiPublicLetoltesTokenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adatvedelmi-tajekoztato': {
      id: '/adatvedelmi-tajekoztato'
      path: '/adatvedelmi-tajekoztato'
      fullPath: '/adatvedelmi-tajekoztato'
      preLoaderRoute: typeof AdatvedelmiTajekoztatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adotanacsadas': {
      id: '/adotanacsadas'
      path: '/adotanacsadas'
      fullPath: '/adotanacsadas'
      preLoaderRoute: typeof AdotanacsadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aszf': {
      id: '/aszf'
      path: '/aszf'
      fullPath: '/aszf'
      preLoaderRoute: typeof AszfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cegaudit': {
      id: '/cegaudit'
      path: '/cegaudit'
      fullPath: '/cegaudit'
      preLoaderRoute: typeof CegauditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-tajekoztato': {
      id: '/cookie-tajekoztato'
      path: '/cookie-tajekoztato'
      fullPath: '/cookie-tajekoztato'
      preLoaderRoute: typeof CookieTajekoztatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digitalis-idomegtakaritasi-audit': {
      id: '/digitalis-idomegtakaritasi-audit'
      path: '/digitalis-idomegtakaritasi-audit'
      fullPath: '/digitalis-idomegtakaritasi-audit'
      preLoaderRoute: typeof DigitalisIdomegtakaritasiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elallas-a-szerzodestol': {
      id: '/elallas-a-szerzodestol'
      path: '/elallas-a-szerzodestol'
      fullPath: '/elallas-a-szerzodestol'
      preLoaderRoute: typeof ElallasASzerzodestolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ev': {
      id: '/ev'
      path: '/ev'
      fullPath: '/ev'
      preLoaderRoute: typeof EvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ev-konyveles': {
      id: '/ev-konyveles'
      path: '/ev-konyveles'
      fullPath: '/ev-konyveles'
      preLoaderRoute: typeof EvKonyvelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fintech-es-bi': {
      id: '/fintech-es-bi'
      path: '/fintech-es-bi'
      fullPath: '/fintech-es-bi'
      preLoaderRoute: typeof FintechEsBiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fizetes-es-teljesites': {
      id: '/fizetes-es-teljesites'
      path: '/fizetes-es-teljesites'
      fullPath: '/fizetes-es-teljesites'
      preLoaderRoute: typeof FizetesEsTeljesitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fogyasztovedelem': {
      id: '/fogyasztovedelem'
      path: '/fogyasztovedelem'
      fullPath: '/fogyasztovedelem'
      preLoaderRoute: typeof FogyasztovedelemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hirlevel-megerosites': {
      id: '/hirlevel-megerosites'
      path: '/hirlevel-megerosites'
      fullPath: '/hirlevel-megerosites'
      preLoaderRoute: typeof HirlevelMegerositesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impresszum': {
      id: '/impresszum'
      path: '/impresszum'
      fullPath: '/impresszum'
      preLoaderRoute: typeof ImpresszumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontrolling': {
      id: '/kontrolling'
      path: '/kontrolling'
      fullPath: '/kontrolling'
      preLoaderRoute: typeof KontrollingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konyveles': {
      id: '/konyveles'
      path: '/konyveles'
      fullPath: '/konyveles'
      preLoaderRoute: typeof KonyvelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konyveloiroda-audit': {
      id: '/konyveloiroda-audit'
      path: '/konyveloiroda-audit'
      fullPath: '/konyveloiroda-audit'
      preLoaderRoute: typeof KonyveloirodaAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konyvvizsgalat': {
      id: '/konyvvizsgalat'
      path: '/konyvvizsgalat'
      fullPath: '/konyvvizsgalat'
      preLoaderRoute: typeof KonyvvizsgalatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konzultacio': {
      id: '/konzultacio'
      path: '/konzultacio'
      fullPath: '/konzultacio'
      preLoaderRoute: typeof KonzultacioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leiratkozas': {
      id: '/leiratkozas'
      path: '/leiratkozas'
      fullPath: '/leiratkozas'
      preLoaderRoute: typeof LeiratkozasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letoltes-hiba': {
      id: '/letoltes-hiba'
      path: '/letoltes-hiba'
      fullPath: '/letoltes-hiba'
      preLoaderRoute: typeof LetoltesHibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/megrendeles': {
      id: '/megrendeles'
      path: '/megrendeles'
      fullPath: '/megrendeles'
      preLoaderRoute: typeof MegrendelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oktatas': {
      id: '/oktatas'
      path: '/oktatas'
      fullPath: '/oktatas'
      preLoaderRoute: typeof OktatasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolam': {
      id: '/rolam'
      path: '/rolam'
      fullPath: '/rolam'
      preLoaderRoute: typeof RolamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/se': {
      id: '/se'
      path: '/se'
      fullPath: '/se'
      preLoaderRoute: typeof SeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/se-bookkeeping': {
      id: '/se-bookkeeping'
      path: '/se-bookkeeping'
      fullPath: '/se-bookkeeping'
      preLoaderRoute: typeof SeBookkeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szolgaltatasaim': {
      id: '/szolgaltatasaim'
      path: '/szolgaltatasaim'
      fullPath: '/szolgaltatasaim'
      preLoaderRoute: typeof SzolgaltatasaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termekeim': {
      id: '/termekeim'
      path: '/termekeim'
      fullPath: '/termekeim'
      preLoaderRoute: typeof TermekeimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billingo-ellenorzes': {
      id: '/admin/billingo-ellenorzes'
      path: '/billingo-ellenorzes'
      fullPath: '/admin/billingo-ellenorzes'
      preLoaderRoute: typeof AdminBillingoEllenorzesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/felhasznalok': {
      id: '/admin/felhasznalok'
      path: '/felhasznalok'
      fullPath: '/admin/felhasznalok'
      preLoaderRoute: typeof AdminFelhasznalokRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fizetes-teszt': {
      id: '/admin/fizetes-teszt'
      path: '/fizetes-teszt'
      fullPath: '/admin/fizetes-teszt'
      preLoaderRoute: typeof AdminFizetesTesztRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/friss-verzio': {
      id: '/admin/friss-verzio'
      path: '/friss-verzio'
      fullPath: '/admin/friss-verzio'
      preLoaderRoute: typeof AdminFrissVerzioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hirlevel': {
      id: '/admin/hirlevel'
      path: '/hirlevel'
      fullPath: '/admin/hirlevel'
      preLoaderRoute: typeof AdminHirlevelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jelszo': {
      id: '/admin/jelszo'
      path: '/jelszo'
      fullPath: '/admin/jelszo'
      preLoaderRoute: typeof AdminJelszoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/katalogus-ellenorzes': {
      id: '/admin/katalogus-ellenorzes'
      path: '/katalogus-ellenorzes'
      fullPath: '/admin/katalogus-ellenorzes'
      preLoaderRoute: typeof AdminKatalogusEllenorzesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kuponok': {
      id: '/admin/kuponok'
      path: '/kuponok'
      fullPath: '/admin/kuponok'
      preLoaderRoute: typeof AdminKuponokRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nav-ellenorzes': {
      id: '/admin/nav-ellenorzes'
      path: '/nav-ellenorzes'
      fullPath: '/admin/nav-ellenorzes'
      preLoaderRoute: typeof AdminNavEllenorzesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rendelesi-audit': {
      id: '/admin/rendelesi-audit'
      path: '/rendelesi-audit'
      fullPath: '/admin/rendelesi-audit'
      preLoaderRoute: typeof AdminRendelesiAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/statisztika': {
      id: '/admin/statisztika'
      path: '/statisztika'
      fullPath: '/admin/statisztika'
      preLoaderRoute: typeof AdminStatisztikaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/szamlazas': {
      id: '/admin/szamlazas'
      path: '/szamlazas'
      fullPath: '/admin/szamlazas'
      preLoaderRoute: typeof AdminSzamlazasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/accounting-firm-audit': {
      id: '/en/accounting-firm-audit'
      path: '/accounting-firm-audit'
      fullPath: '/en/accounting-firm-audit'
      preLoaderRoute: typeof EnAccountingFirmAuditRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/bookkeeping': {
      id: '/en/bookkeeping'
      path: '/bookkeeping'
      fullPath: '/en/bookkeeping'
      preLoaderRoute: typeof EnBookkeepingRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/company-audit': {
      id: '/en/company-audit'
      path: '/company-audit'
      fullPath: '/en/company-audit'
      preLoaderRoute: typeof EnCompanyAuditRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/controlling': {
      id: '/en/controlling'
      path: '/controlling'
      fullPath: '/en/controlling'
      preLoaderRoute: typeof EnControllingRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/digital-time-saving-audit': {
      id: '/en/digital-time-saving-audit'
      path: '/digital-time-saving-audit'
      fullPath: '/en/digital-time-saving-audit'
      preLoaderRoute: typeof EnDigitalTimeSavingAuditRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/fintech-and-bi': {
      id: '/en/fintech-and-bi'
      path: '/fintech-and-bi'
      fullPath: '/en/fintech-and-bi'
      preLoaderRoute: typeof EnFintechAndBiRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/services': {
      id: '/en/services'
      path: '/services'
      fullPath: '/en/services'
      preLoaderRoute: typeof EnServicesRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/sole-trader-bookkeeping': {
      id: '/en/sole-trader-bookkeeping'
      path: '/sole-trader-bookkeeping'
      fullPath: '/en/sole-trader-bookkeeping'
      preLoaderRoute: typeof EnSoleTraderBookkeepingRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/statutory-audit': {
      id: '/en/statutory-audit'
      path: '/statutory-audit'
      fullPath: '/en/statutory-audit'
      preLoaderRoute: typeof EnStatutoryAuditRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/tax-advisory': {
      id: '/en/tax-advisory'
      path: '/tax-advisory'
      fullPath: '/en/tax-advisory'
      preLoaderRoute: typeof EnTaxAdvisoryRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/training': {
      id: '/en/training'
      path: '/training'
      fullPath: '/en/training'
      preLoaderRoute: typeof EnTrainingRouteImport
      parentRoute: typeof EnRoute
    }
    '/kalkulatorok/': {
      id: '/kalkulatorok/'
      path: '/kalkulatorok'
      fullPath: '/kalkulatorok/'
      preLoaderRoute: typeof KalkulatorokIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulatorok/atalanyado': {
      id: '/kalkulatorok/atalanyado'
      path: '/kalkulatorok/atalanyado'
      fullPath: '/kalkulatorok/atalanyado'
      preLoaderRoute: typeof KalkulatorokAtalanyadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulatorok/berteszt': {
      id: '/kalkulatorok/berteszt'
      path: '/kalkulatorok/berteszt'
      fullPath: '/kalkulatorok/berteszt'
      preLoaderRoute: typeof KalkulatorokBertesztRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulatorok/invoice-dates': {
      id: '/kalkulatorok/invoice-dates'
      path: '/kalkulatorok/invoice-dates'
      fullPath: '/kalkulatorok/invoice-dates'
      preLoaderRoute: typeof KalkulatorokInvoiceDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulatorok/jovedelemado': {
      id: '/kalkulatorok/jovedelemado'
      path: '/kalkulatorok/jovedelemado'
      fullPath: '/kalkulatorok/jovedelemado'
      preLoaderRoute: typeof KalkulatorokJovedelemadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulatorok/szamla-datumok': {
      id: '/kalkulatorok/szamla-datumok'
      path: '/kalkulatorok/szamla-datumok'
      fullPath: '/kalkulatorok/szamla-datumok'
      preLoaderRoute: typeof KalkulatorokSzamlaDatumokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/megrendeles_/koszonjuk': {
      id: '/megrendeles_/koszonjuk'
      path: '/megrendeles/koszonjuk'
      fullPath: '/megrendeles/koszonjuk'
      preLoaderRoute: typeof MegrendelesKoszonjukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/$slug': {
      id: '/termek/$slug'
      path: '/termek/$slug'
      fullPath: '/termek/$slug'
      preLoaderRoute: typeof TermekSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/a60-osszesito-nyilatkozat-xml': {
      id: '/termek/a60-osszesito-nyilatkozat-xml'
      path: '/termek/a60-osszesito-nyilatkozat-xml'
      fullPath: '/termek/a60-osszesito-nyilatkozat-xml'
      preLoaderRoute: typeof TermekA60OsszesitoNyilatkozatXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/adofolyoszamla-egyezteto': {
      id: '/termek/adofolyoszamla-egyezteto'
      path: '/termek/adofolyoszamla-egyezteto'
      fullPath: '/termek/adofolyoszamla-egyezteto'
      preLoaderRoute: typeof TermekAdofolyoszamlaEgyeztetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/afa-ev65-xml-generalo': {
      id: '/termek/afa-ev65-xml-generalo'
      path: '/termek/afa-ev65-xml-generalo'
      fullPath: '/termek/afa-ev65-xml-generalo'
      preLoaderRoute: typeof TermekAfaEv65XmlGeneraloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/auditxml-ellenorzo-javito': {
      id: '/termek/auditxml-ellenorzo-javito'
      path: '/termek/auditxml-ellenorzo-javito'
      fullPath: '/termek/auditxml-ellenorzo-javito'
      preLoaderRoute: typeof TermekAuditxmlEllenorzoJavitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/berszamfejto': {
      id: '/termek/berszamfejto'
      path: '/termek/berszamfejto'
      fullPath: '/termek/berszamfejto'
      preLoaderRoute: typeof TermekBerszamfejtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/beszamolo': {
      id: '/termek/beszamolo'
      path: '/termek/beszamolo'
      fullPath: '/termek/beszamolo'
      preLoaderRoute: typeof TermekBeszamoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/cegkivonat-excel-konverter': {
      id: '/termek/cegkivonat-excel-konverter'
      path: '/termek/cegkivonat-excel-konverter'
      fullPath: '/termek/cegkivonat-excel-konverter'
      preLoaderRoute: typeof TermekCegkivonatExcelKonverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/devizabank': {
      id: '/termek/devizabank'
      path: '/termek/devizabank'
      fullPath: '/termek/devizabank'
      preLoaderRoute: typeof TermekDevizabankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/havi-riport': {
      id: '/termek/havi-riport'
      path: '/termek/havi-riport'
      fullPath: '/termek/havi-riport'
      preLoaderRoute: typeof TermekHaviRiportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/havi-riport-en': {
      id: '/termek/havi-riport-en'
      path: '/termek/havi-riport-en'
      fullPath: '/termek/havi-riport-en'
      preLoaderRoute: typeof TermekHaviRiportEnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/ifrs-konszolidalo': {
      id: '/termek/ifrs-konszolidalo'
      path: '/termek/ifrs-konszolidalo'
      fullPath: '/termek/ifrs-konszolidalo'
      preLoaderRoute: typeof TermekIfrsKonszolidaloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/ingatlanalap-mnb-jelentes-elokeszito': {
      id: '/termek/ingatlanalap-mnb-jelentes-elokeszito'
      path: '/termek/ingatlanalap-mnb-jelentes-elokeszito'
      fullPath: '/termek/ingatlanalap-mnb-jelentes-elokeszito'
      preLoaderRoute: typeof TermekIngatlanalapMnbJelentesElokeszitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/kamatlekerdezo-potlekszamito': {
      id: '/termek/kamatlekerdezo-potlekszamito'
      path: '/termek/kamatlekerdezo-potlekszamito'
      fullPath: '/termek/kamatlekerdezo-potlekszamito'
      preLoaderRoute: typeof TermekKamatlekerdezoPotlekszamitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/kulcs-nyito-vegyes-konyvelo': {
      id: '/termek/kulcs-nyito-vegyes-konyvelo'
      path: '/termek/kulcs-nyito-vegyes-konyvelo'
      fullPath: '/termek/kulcs-nyito-vegyes-konyvelo'
      preLoaderRoute: typeof TermekKulcsNyitoVegyesKonyveloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/kulcs-soft-kulfoldi-szamla-import': {
      id: '/termek/kulcs-soft-kulfoldi-szamla-import'
      path: '/termek/kulcs-soft-kulfoldi-szamla-import'
      fullPath: '/termek/kulcs-soft-kulfoldi-szamla-import'
      preLoaderRoute: typeof TermekKulcsSoftKulfoldiSzamlaImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/mnb-era-jelentesgenerator': {
      id: '/termek/mnb-era-jelentesgenerator'
      path: '/termek/mnb-era-jelentesgenerator'
      fullPath: '/termek/mnb-era-jelentesgenerator'
      preLoaderRoute: typeof TermekMnbEraJelentesgeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/nav-online-szamla-letolto': {
      id: '/termek/nav-online-szamla-letolto'
      path: '/termek/nav-online-szamla-letolto'
      fullPath: '/termek/nav-online-szamla-letolto'
      preLoaderRoute: typeof TermekNavOnlineSzamlaLetoltoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/nav-penztargep-letolto': {
      id: '/termek/nav-penztargep-letolto'
      path: '/termek/nav-penztargep-letolto'
      fullPath: '/termek/nav-penztargep-letolto'
      preLoaderRoute: typeof TermekNavPenztargepLetoltoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/nav-torzsszam-partnerellenorzo': {
      id: '/termek/nav-torzsszam-partnerellenorzo'
      path: '/termek/nav-torzsszam-partnerellenorzo'
      fullPath: '/termek/nav-torzsszam-partnerellenorzo'
      preLoaderRoute: typeof TermekNavTorzsszamPartnerellenorzoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/pdf-excel-konverter': {
      id: '/termek/pdf-excel-konverter'
      path: '/termek/pdf-excel-konverter'
      fullPath: '/termek/pdf-excel-konverter'
      preLoaderRoute: typeof TermekPdfExcelKonverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/penzszam-kulfoldi-szamla-import': {
      id: '/termek/penzszam-kulfoldi-szamla-import'
      path: '/termek/penzszam-kulfoldi-szamla-import'
      fullPath: '/termek/penzszam-kulfoldi-szamla-import'
      preLoaderRoute: typeof TermekPenzszamKulfoldiSzamlaImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/rlb-bank-konverter': {
      id: '/termek/rlb-bank-konverter'
      path: '/termek/rlb-bank-konverter'
      fullPath: '/termek/rlb-bank-konverter'
      preLoaderRoute: typeof TermekRlbBankKonverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/rlb-bank-konverter-pro': {
      id: '/termek/rlb-bank-konverter-pro'
      path: '/termek/rlb-bank-konverter-pro'
      fullPath: '/termek/rlb-bank-konverter-pro'
      preLoaderRoute: typeof TermekRlbBankKonverterProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/rlb-kulfoldi-szamla-import': {
      id: '/termek/rlb-kulfoldi-szamla-import'
      path: '/termek/rlb-kulfoldi-szamla-import'
      fullPath: '/termek/rlb-kulfoldi-szamla-import'
      preLoaderRoute: typeof TermekRlbKulfoldiSzamlaImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/rlb-nyito-vegyes-konyvelo': {
      id: '/termek/rlb-nyito-vegyes-konyvelo'
      path: '/termek/rlb-nyito-vegyes-konyvelo'
      fullPath: '/termek/rlb-nyito-vegyes-konyvelo'
      preLoaderRoute: typeof TermekRlbNyitoVegyesKonyveloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/sup-nyito-vegyes-konyvelo': {
      id: '/termek/sup-nyito-vegyes-konyvelo'
      path: '/termek/sup-nyito-vegyes-konyvelo'
      fullPath: '/termek/sup-nyito-vegyes-konyvelo'
      preLoaderRoute: typeof TermekSupNyitoVegyesKonyveloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/szamviteli-konszolidalo': {
      id: '/termek/szamviteli-konszolidalo'
      path: '/termek/szamviteli-konszolidalo'
      fullPath: '/termek/szamviteli-konszolidalo'
      preLoaderRoute: typeof TermekSzamviteliKonszolidaloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/telefonszamla-konyvelo': {
      id: '/termek/telefonszamla-konyvelo'
      path: '/termek/telefonszamla-konyvelo'
      fullPath: '/termek/telefonszamla-konyvelo'
      preLoaderRoute: typeof TermekTelefonszamlaKonyveloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/ugyfelkapu-totp-manager': {
      id: '/termek/ugyfelkapu-totp-manager'
      path: '/termek/ugyfelkapu-totp-manager'
      fullPath: '/termek/ugyfelkapu-totp-manager'
      preLoaderRoute: typeof TermekUgyfelkapuTotpManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/univerzalis-bank-konverter': {
      id: '/termek/univerzalis-bank-konverter'
      path: '/termek/univerzalis-bank-konverter'
      fullPath: '/termek/univerzalis-bank-konverter'
      preLoaderRoute: typeof TermekUniverzalisBankKonverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/utalasi-csomag-keszito': {
      id: '/termek/utalasi-csomag-keszito'
      path: '/termek/utalasi-csomag-keszito'
      fullPath: '/termek/utalasi-csomag-keszito'
      preLoaderRoute: typeof TermekUtalasiCsomagKeszitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/utnyilvantartas-kikuldetesi-rendelveny': {
      id: '/termek/utnyilvantartas-kikuldetesi-rendelveny'
      path: '/termek/utnyilvantartas-kikuldetesi-rendelveny'
      fullPath: '/termek/utnyilvantartas-kikuldetesi-rendelveny'
      preLoaderRoute: typeof TermekUtnyilvantartasKikuldetesiRendelvenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termek/wifi-jelszo-nezo': {
      id: '/termek/wifi-jelszo-nezo'
      path: '/termek/wifi-jelszo-nezo'
      fullPath: '/termek/wifi-jelszo-nezo'
      preLoaderRoute: typeof TermekWifiJelszoNezoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billingo/webhook': {
      id: '/api/public/billingo/webhook'
      path: '/api/public/billingo/webhook'
      fullPath: '/api/public/billingo/webhook'
      preLoaderRoute: typeof ApiPublicBillingoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/katalogus-audit/cron': {
      id: '/api/public/katalogus-audit/cron'
      path: '/api/public/katalogus-audit/cron'
      fullPath: '/api/public/katalogus-audit/cron'
      preLoaderRoute: typeof ApiPublicKatalogusAuditCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/letoltes/$token': {
      id: '/api/public/letoltes/$token'
      path: '/api/public/letoltes/$token'
      fullPath: '/api/public/letoltes/$token'
      preLoaderRoute: typeof ApiPublicLetoltesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBillingoEllenorzesRoute: typeof AdminBillingoEllenorzesRoute
  AdminFelhasznalokRoute: typeof AdminFelhasznalokRoute
  AdminFizetesTesztRoute: typeof AdminFizetesTesztRoute
  AdminFrissVerzioRoute: typeof AdminFrissVerzioRoute
  AdminHirlevelRoute: typeof AdminHirlevelRoute
  AdminJelszoRoute: typeof AdminJelszoRoute
  AdminKatalogusEllenorzesRoute: typeof AdminKatalogusEllenorzesRoute
  AdminKuponokRoute: typeof AdminKuponokRoute
  AdminNavEllenorzesRoute: typeof AdminNavEllenorzesRoute
  AdminRendelesiAuditRoute: typeof AdminRendelesiAuditRoute
  AdminStatisztikaRoute: typeof AdminStatisztikaRoute
  AdminSzamlazasRoute: typeof AdminSzamlazasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingoEllenorzesRoute: AdminBillingoEllenorzesRoute,
  AdminFelhasznalokRoute: AdminFelhasznalokRoute,
  AdminFizetesTesztRoute: AdminFizetesTesztRoute,
  AdminFrissVerzioRoute: AdminFrissVerzioRoute,
  AdminHirlevelRoute: AdminHirlevelRoute,
  AdminJelszoRoute: AdminJelszoRoute,
  AdminKatalogusEllenorzesRoute: AdminKatalogusEllenorzesRoute,
  AdminKuponokRoute: AdminKuponokRoute,
  AdminNavEllenorzesRoute: AdminNavEllenorzesRoute,
  AdminRendelesiAuditRoute: AdminRendelesiAuditRoute,
  AdminStatisztikaRoute: AdminStatisztikaRoute,
  AdminSzamlazasRoute: AdminSzamlazasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnAccountingFirmAuditRoute: typeof EnAccountingFirmAuditRoute
  EnBookkeepingRoute: typeof EnBookkeepingRoute
  EnCompanyAuditRoute: typeof EnCompanyAuditRoute
  EnContactRoute: typeof EnContactRoute
  EnControllingRoute: typeof EnControllingRoute
  EnDigitalTimeSavingAuditRoute: typeof EnDigitalTimeSavingAuditRoute
  EnFintechAndBiRoute: typeof EnFintechAndBiRoute
  EnServicesRoute: typeof EnServicesRoute
  EnSoleTraderBookkeepingRoute: typeof EnSoleTraderBookkeepingRoute
  EnStatutoryAuditRoute: typeof EnStatutoryAuditRoute
  EnTaxAdvisoryRoute: typeof EnTaxAdvisoryRoute
  EnTrainingRoute: typeof EnTrainingRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnAccountingFirmAuditRoute: EnAccountingFirmAuditRoute,
  EnBookkeepingRoute: EnBookkeepingRoute,
  EnCompanyAuditRoute: EnCompanyAuditRoute,
  EnContactRoute: EnContactRoute,
  EnControllingRoute: EnControllingRoute,
  EnDigitalTimeSavingAuditRoute: EnDigitalTimeSavingAuditRoute,
  EnFintechAndBiRoute: EnFintechAndBiRoute,
  EnServicesRoute: EnServicesRoute,
  EnSoleTraderBookkeepingRoute: EnSoleTraderBookkeepingRoute,
  EnStatutoryAuditRoute: EnStatutoryAuditRoute,
  EnTaxAdvisoryRoute: EnTaxAdvisoryRoute,
  EnTrainingRoute: EnTrainingRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdatvedelmiTajekoztatoRoute: AdatvedelmiTajekoztatoRoute,
  AdminRoute: AdminRouteWithChildren,
  AdotanacsadasRoute: AdotanacsadasRoute,
  AszfRoute: AszfRoute,
  CegauditRoute: CegauditRoute,
  CookieTajekoztatoRoute: CookieTajekoztatoRoute,
  DigitalisIdomegtakaritasiAuditRoute: DigitalisIdomegtakaritasiAuditRoute,
  ElallasASzerzodestolRoute: ElallasASzerzodestolRoute,
  EnRoute: EnRouteWithChildren,
  EvRoute: EvRoute,
  EvKonyvelesRoute: EvKonyvelesRoute,
  FintechEsBiRoute: FintechEsBiRoute,
  FizetesEsTeljesitesRoute: FizetesEsTeljesitesRoute,
  FogyasztovedelemRoute: FogyasztovedelemRoute,
  HirlevelMegerositesRoute: HirlevelMegerositesRoute,
  ImpresszumRoute: ImpresszumRoute,
  KapcsolatRoute: KapcsolatRoute,
  KontrollingRoute: KontrollingRoute,
  KonyvelesRoute: KonyvelesRoute,
  KonyveloirodaAuditRoute: KonyveloirodaAuditRoute,
  KonyvvizsgalatRoute: KonyvvizsgalatRoute,
  KonzultacioRoute: KonzultacioRoute,
  LeiratkozasRoute: LeiratkozasRoute,
  LetoltesHibaRoute: LetoltesHibaRoute,
  MegrendelesRoute: MegrendelesRoute,
  OktatasRoute: OktatasRoute,
  RolamRoute: RolamRoute,
  SeRoute: SeRoute,
  SeBookkeepingRoute: SeBookkeepingRoute,
  SzolgaltatasaimRoute: SzolgaltatasaimRoute,
  TermekeimRoute: TermekeimRoute,
  KalkulatorokAtalanyadoRoute: KalkulatorokAtalanyadoRoute,
  KalkulatorokBertesztRoute: KalkulatorokBertesztRoute,
  KalkulatorokInvoiceDatesRoute: KalkulatorokInvoiceDatesRoute,
  KalkulatorokJovedelemadoRoute: KalkulatorokJovedelemadoRoute,
  KalkulatorokSzamlaDatumokRoute: KalkulatorokSzamlaDatumokRoute,
  MegrendelesKoszonjukRoute: MegrendelesKoszonjukRoute,
  TermekSlugRoute: TermekSlugRoute,
  TermekA60OsszesitoNyilatkozatXmlRoute: TermekA60OsszesitoNyilatkozatXmlRoute,
  TermekAdofolyoszamlaEgyeztetoRoute: TermekAdofolyoszamlaEgyeztetoRoute,
  TermekAfaEv65XmlGeneraloRoute: TermekAfaEv65XmlGeneraloRoute,
  TermekAuditxmlEllenorzoJavitoRoute: TermekAuditxmlEllenorzoJavitoRoute,
  TermekBerszamfejtoRoute: TermekBerszamfejtoRoute,
  TermekBeszamoloRoute: TermekBeszamoloRoute,
  TermekCegkivonatExcelKonverterRoute: TermekCegkivonatExcelKonverterRoute,
  TermekDevizabankRoute: TermekDevizabankRoute,
  TermekHaviRiportRoute: TermekHaviRiportRoute,
  TermekHaviRiportEnRoute: TermekHaviRiportEnRoute,
  TermekIfrsKonszolidaloRoute: TermekIfrsKonszolidaloRoute,
  TermekIngatlanalapMnbJelentesElokeszitoRoute:
    TermekIngatlanalapMnbJelentesElokeszitoRoute,
  TermekKamatlekerdezoPotlekszamitoRoute:
    TermekKamatlekerdezoPotlekszamitoRoute,
  TermekKulcsNyitoVegyesKonyveloRoute: TermekKulcsNyitoVegyesKonyveloRoute,
  TermekKulcsSoftKulfoldiSzamlaImportRoute:
    TermekKulcsSoftKulfoldiSzamlaImportRoute,
  TermekMnbEraJelentesgeneratorRoute: TermekMnbEraJelentesgeneratorRoute,
  TermekNavOnlineSzamlaLetoltoRoute: TermekNavOnlineSzamlaLetoltoRoute,
  TermekNavPenztargepLetoltoRoute: TermekNavPenztargepLetoltoRoute,
  TermekNavTorzsszamPartnerellenorzoRoute:
    TermekNavTorzsszamPartnerellenorzoRoute,
  TermekPdfExcelKonverterRoute: TermekPdfExcelKonverterRoute,
  TermekPenzszamKulfoldiSzamlaImportRoute:
    TermekPenzszamKulfoldiSzamlaImportRoute,
  TermekRlbBankKonverterRoute: TermekRlbBankKonverterRoute,
  TermekRlbBankKonverterProRoute: TermekRlbBankKonverterProRoute,
  TermekRlbKulfoldiSzamlaImportRoute: TermekRlbKulfoldiSzamlaImportRoute,
  TermekRlbNyitoVegyesKonyveloRoute: TermekRlbNyitoVegyesKonyveloRoute,
  TermekSupNyitoVegyesKonyveloRoute: TermekSupNyitoVegyesKonyveloRoute,
  TermekSzamviteliKonszolidaloRoute: TermekSzamviteliKonszolidaloRoute,
  TermekTelefonszamlaKonyveloRoute: TermekTelefonszamlaKonyveloRoute,
  TermekUgyfelkapuTotpManagerRoute: TermekUgyfelkapuTotpManagerRoute,
  TermekUniverzalisBankKonverterRoute: TermekUniverzalisBankKonverterRoute,
  TermekUtalasiCsomagKeszitoRoute: TermekUtalasiCsomagKeszitoRoute,
  TermekUtnyilvantartasKikuldetesiRendelvenyRoute:
    TermekUtnyilvantartasKikuldetesiRendelvenyRoute,
  TermekWifiJelszoNezoRoute: TermekWifiJelszoNezoRoute,
  KalkulatorokIndexRoute: KalkulatorokIndexRoute,
  ApiPublicBillingoWebhookRoute: ApiPublicBillingoWebhookRoute,
  ApiPublicKatalogusAuditCronRoute: ApiPublicKatalogusAuditCronRoute,
  ApiPublicLetoltesTokenRoute: ApiPublicLetoltesTokenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
